<?php

namespace AppBundle\Repository;

/**
 * CoureurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoureurRepository extends \Doctrine\ORM\EntityRepository
{
}
